In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets

In [2]:
#iris dataset
iris = pd.read_csv('Iris.csv')

In [3]:
iris.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [4]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
Id               150 non-null int64
SepalLengthCm    150 non-null float64
SepalWidthCm     150 non-null float64
PetalLengthCm    150 non-null float64
PetalWidthCm     150 non-null float64
Species          150 non-null object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [5]:
iris.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [6]:
#drop id column
df = iris.drop('Id',axis=1)

In [7]:
df.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [8]:
df.Species.unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [9]:
#Naives Bayes

#split into test-train
from sklearn.model_selection import train_test_split
X = df.iloc[:,:4]
y = df['Species']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2,random_state=100)

In [10]:
X_train.shape

(120, 4)

In [11]:
X_test.shape

(30, 4)

In [12]:
#scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [13]:
#In this example we are using Gaussian model 
#there are several other models such as Bernoulli, Categorical and Multinomial
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [14]:
y_pred = classifier.predict(X_train) 

In [15]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_train, y_pred)
print(cm)
from sklearn.metrics import accuracy_score 
print ("Accuracy : ", accuracy_score(y_train, y_pred))

[[39  0  0]
 [ 0 42  2]
 [ 0  3 34]]
Accuracy :  0.9583333333333334


In [16]:
#Predicting the test
y_pred = classifier.predict(X_test) 
y_pred

array(['Iris-virginica', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-virginica',
       'Iris-setosa', 'Iris-setosa', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica'], dtype='<U15')

In [17]:
#Confusion matrix and accuracy
cm = confusion_matrix(y_test, y_pred)
print(cm) 
print ("Accuracy : ", accuracy_score(y_test, y_pred))

[[11  0  0]
 [ 0  5  1]
 [ 0  0 13]]
Accuracy :  0.9666666666666667


In [18]:
#K-NN model 

from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 2, metric = 'minkowski', p = 2, n_jobs = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier(n_jobs=2, n_neighbors=2)

In [19]:
#Prediciting the results
y_pred = classifier.predict(X_test) 
y_pred

array(['Iris-virginica', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-virginica',
       'Iris-setosa', 'Iris-setosa', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [20]:
#Confusion matrix and accuracy
cm = confusion_matrix(y_test, y_pred)
print(cm) 
print ("Accuracy : ", accuracy_score(y_test, y_pred))

[[11  0  0]
 [ 0  6  0]
 [ 0  1 12]]
Accuracy :  0.9666666666666667


In [21]:
#Comparing real to predicted
df = pd.DataFrame({'Real Values':y_test, 'Predicted Values':y_pred})

In [22]:
print(df.head)

<bound method NDFrame.head of          Real Values Predicted Values
128   Iris-virginica   Iris-virginica
11       Iris-setosa      Iris-setosa
118   Iris-virginica   Iris-virginica
15       Iris-setosa      Iris-setosa
123   Iris-virginica   Iris-virginica
135   Iris-virginica   Iris-virginica
32       Iris-setosa      Iris-setosa
1        Iris-setosa      Iris-setosa
116   Iris-virginica   Iris-virginica
45       Iris-setosa      Iris-setosa
40       Iris-setosa      Iris-setosa
115   Iris-virginica   Iris-virginica
26       Iris-setosa      Iris-setosa
28       Iris-setosa      Iris-setosa
145   Iris-virginica   Iris-virginica
97   Iris-versicolor  Iris-versicolor
62   Iris-versicolor  Iris-versicolor
77   Iris-versicolor  Iris-versicolor
122   Iris-virginica   Iris-virginica
112   Iris-virginica   Iris-virginica
125   Iris-virginica   Iris-virginica
31       Iris-setosa      Iris-setosa
146   Iris-virginica  Iris-versicolor
29       Iris-setosa      Iris-setosa
69   Iris-versicolor